/**
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 **/

/**
 * @file sdp2poly.cpp
 * @ingroup Converters
 * @author Bertrand Kerautret (\c kerautre@loria.fr )
 * LORIA (CNRS, UMR 7503), University of Lorraine, France
 *
 * @date 2016/07/15
 *
 * Source file of the tool sdp2poly
 *
 * This file is part of the DGtal library/DGtalTools Project.
 */

///////////////////////////////////////////////////////////////////////////////
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/readers/PointListReader.h"


#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
///////////////////////////////////////////////////////////////////////////////
using namespace std;
using namespace DGtal;
///////////////////////////////////////////////////////////////////////////////
namespace po = boost::program_options;


/**
 @page sdp2poly sdp2poly
 @section sdp2poly_sec sdp2poly

 @ingroup convertertools
 @brief  Description of the tool...

 @b Usage:   sdp2poly [input]

 @b Allowed @b options @b are :
 
 @code
  -h [ --help ]           display this message
  -i [ --input ] arg      an input file... 
  -p [ --parameter] arg   a double parameter...
 @endcode

 @b Example: 

 @code
   	sdp2poly -i  $DGtal/examples/samples/....
 @endcode

 @image html ressdp2poly.png "Example of result. "

 @see
 @ref sdp2poly.cpp

 */


int main( int argc, char** argv )
{
  // parse command line -------------------------------------------------------
  po::options_description general_opt("Allowed options are");
  general_opt.add_options()
    ("help,h", "display this message")
    ("input,i", po::value<std::string >(), "an input sdp file." )
    ("output,o", po::value<std::string >(), "an output poly file." );

  bool parseOK=true;
  po::variables_map vm;
  try
    {
      po::store(po::parse_command_line(argc, argv, general_opt), vm);
    }
  catch(const std::exception& ex)
    {
      parseOK=false;
      trace.info()<< "Error checking program options: "<< ex.what()<< endl;
    }
  

  // check if min arguments are given and tools description ------------------
  po::notify(vm);
  if( !parseOK || vm.count("help")||argc<=1)
    {
      std::cout << "Usage: " << argv[0] << " [input]\n"
                << "The tools description... \n"
                << general_opt << "\n"
                << "Typical use example:\n \t sdp2poly -i ... \n";
      return 0;
    }  
  if(! vm.count("input"))
    {
      trace.error() << " The file name was not defined" << endl;
      return 1;
    }
  
  

  //  recover the  args ----------------------------------------------------
  string inputFileName = vm["input"].as<string>();
  string outputFileName = vm["output"].as<string>();
  typedef DGtal::Z2i::RealPoint Point;
  std::vector<Point> vectPt = PointListReader<Point>::getPointsFromFile(inputFileName);
  std::ofstream out;
  out.open(outputFileName.c_str(),ios::binary); 
  
  
  // Transforming in poly format  --------------------------------------------------
  // (see http://www.cs.cmu.edu/~quake/triangle.poly.html)
  
  // Following lines: <vertex #> <x> <y> [attributes] [boundary marker]
  // One line: <# of segments> <# of boundary markers (0 or 1)>
  // Following lines: <segment #> <endpoint> <endpoint> [boundary marker]
  // One line: <# of holes>
  // Following lines: <hole #> <x> <y> 
  // Optional line: <# of regional attributes and/or area constraints>
  // Optional following lines: <region #> <x> <y> <attribute> <maximum area>

  out << "# poly format generated by sdp2poly tool from DGtalTools project (https://github.com/DGtal-team/DGtalTools) " << std::endl; 
  // First line: <# of vertices> <dimension (must be 2)> <# of attributes> <# of boundary markers (0 or 1)>
  out << vectPt.size() << " 2  0 0" << std::endl;
  unsigned int i = 0;
  for(const auto &p: vectPt)
    {
      out << i << " " << p[0] << " " << p[1] <<  " " << 0 << std::endl;
      i++;
    }
  out << vectPt.size() << " 0" << std::endl;
  i = 0;
  for(const auto &p: vectPt)
    {
      out << i << " " << i  << " " << (i+1)%vectPt.size() <<  " " << 0 << std::endl;
      i++;
    }

  out << 0 << std::endl;

  out.close();

  return 0;
}

